# Generated by Django 4.2.6 on 2023-10-31 11:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(null=True, upload_to="images/")),
                ("fname", models.CharField(max_length=100, null=True)),
                ("lname", models.CharField(max_length=100, null=True)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("phone", models.CharField(max_length=14, null=True)),
                ("address", models.TextField(null=True)),
                ("about", ckeditor.fields.RichTextField(null=True)),
                ("linkedin", models.URLField(null=True)),
                ("github", models.URLField(null=True)),
                ("twitter", models.URLField(null=True)),
                ("facebook", models.URLField(null=True)),
            ],
        ),
    ]
