# Generated by Django 4.2.6 on 2023-10-31 11:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("port_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inter_date", models.DateField(blank=True, null=True)),
                ("Interests", ckeditor.fields.RichTextField(null=True)),
            ],
        ),
    ]
