# Generated by Django 4.2.6 on 2023-10-31 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("port_app", "0002_inter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inter",
            name="inter_date",
        ),
    ]
