# Generated by Django 4.2.6 on 2023-10-31 12:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("port_app", "0003_remove_inter_inter_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_pos_1", models.CharField(max_length=255, null=True)),
                ("company_nam_1", models.CharField(max_length=255, null=True)),
                ("start_date_1", models.DateField(blank=True, null=True)),
                ("end_date_1", models.DateField(blank=True, null=True)),
                ("job_respo_1", ckeditor.fields.RichTextField(null=True)),
                ("job_pos_2", models.CharField(max_length=255, null=True)),
                ("company_nam_2", models.CharField(max_length=255, null=True)),
                ("start_date_2", models.DateField(blank=True, null=True)),
                ("end_date_2", models.DateField(blank=True, null=True)),
                ("job_respo_2", ckeditor.fields.RichTextField(null=True)),
                ("job_pos_3", models.CharField(max_length=255, null=True)),
                ("company_nam_3", models.CharField(max_length=255, null=True)),
                ("start_date_3", models.DateField(blank=True, null=True)),
                ("end_date_3", models.DateField(blank=True, null=True)),
                ("job_respo_3", ckeditor.fields.RichTextField(null=True)),
                ("job_pos_4", models.CharField(max_length=255, null=True)),
                ("company_nam_4", models.CharField(max_length=255, null=True)),
                ("start_date_4", models.DateField(blank=True, null=True)),
                ("end_date_4", models.DateField(blank=True, null=True)),
                ("job_respo_4", ckeditor.fields.RichTextField(null=True)),
            ],
        ),
    ]
