# Generated by Django 4.2.6 on 2023-10-31 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("port_app", "0004_experience"),
    ]

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("edu_inst_1", models.CharField(max_length=255, null=True)),
                ("edu_dept_1", models.CharField(max_length=255, null=True)),
                ("edu_deg_1", models.CharField(max_length=255, null=True)),
                ("edu_gpa_1", models.CharField(max_length=255, null=True)),
                ("edu_std_1", models.DateField(blank=True, null=True)),
                ("edu_end_1", models.DateField(blank=True, null=True)),
                ("edu_inst_2", models.CharField(max_length=255, null=True)),
                ("edu_dept_2", models.CharField(max_length=255, null=True)),
                ("edu_deg_2", models.CharField(max_length=255, null=True)),
                ("edu_gpa_2", models.CharField(max_length=255, null=True)),
                ("edu_std_2", models.DateField(blank=True, null=True)),
                ("edu_end_2", models.DateField(blank=True, null=True)),
                ("edu_inst_3", models.CharField(max_length=255, null=True)),
                ("edu_dept_3", models.CharField(max_length=255, null=True)),
                ("edu_deg_3", models.CharField(max_length=255, null=True)),
                ("edu_gpa_3", models.CharField(max_length=255, null=True)),
                ("edu_std_3", models.DateField(blank=True, null=True)),
                ("edu_end_3", models.DateField(blank=True, null=True)),
                ("edu_inst_4", models.CharField(max_length=255, null=True)),
                ("edu_dept_4", models.CharField(max_length=255, null=True)),
                ("edu_deg_4", models.CharField(max_length=255, null=True)),
                ("edu_gpa_4", models.CharField(max_length=255, null=True)),
                ("edu_std_4", models.DateField(blank=True, null=True)),
                ("edu_end_4", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
