# Generated by Django 4.2.6 on 2023-10-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("port_app", "0005_education"),
    ]

    operations = [
        migrations.CreateModel(
            name="Awr_Cer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("AC_1", models.CharField(max_length=255, null=True)),
                ("AC_2", models.CharField(max_length=255, null=True)),
                ("AC_3", models.CharField(max_length=255, null=True)),
                ("AC_4", models.CharField(max_length=255, null=True)),
                ("AC_5", models.CharField(max_length=255, null=True)),
                ("AC_6", models.CharField(max_length=255, null=True)),
                ("AC_7", models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
