# Generated by Django 4.2.6 on 2023-10-31 20:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("port_app", "0006_awr_cer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pt_1", models.ImageField(null=True, upload_to="icons/")),
                ("plt_2", models.ImageField(null=True, upload_to="icons/")),
                ("plt_3", models.ImageField(null=True, upload_to="icons/")),
                ("plt_4", models.ImageField(null=True, upload_to="icons/")),
                ("plt_5", models.ImageField(null=True, upload_to="icons/")),
                ("plt_6", models.ImageField(null=True, upload_to="icons/")),
                ("plt_7", models.ImageField(null=True, upload_to="icons/")),
                ("plt_8", models.ImageField(null=True, upload_to="icons/")),
                ("plt_9", models.ImageField(null=True, upload_to="icons/")),
                ("plt_10", models.ImageField(null=True, upload_to="icons/")),
                ("workflow", ckeditor.fields.RichTextField(null=True)),
            ],
        ),
    ]
