# Generated by Django 4.2.6 on 2023-10-31 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("port_app", "0007_skills"),
    ]

    operations = [
        migrations.RenameField(
            model_name="skills",
            old_name="pt_1",
            new_name="plt_1",
        ),
    ]
