# Generated by Django 4.2.6 on 2023-10-31 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("port_app", "0008_rename_pt_1_skills_plt_1"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(null=True, upload_to="images/")),
            ],
        ),
        migrations.RemoveField(
            model_name="about",
            name="image",
        ),
    ]
